version: 0.2
env:
   parameter-store:
     SONARQUBE_TOKEN: "SonarQubeToken"
     SONARQUBE_ENDPOINT: "SonarQubeEndpoint"

phases:
  pre_build:
     install:
       commands:
         - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
         - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
         - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
   
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
      - mvn sonar-scanner
      - mvn sonar:sonar
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/petclinic.war petclinic.war
     
artifacts:
  files:
      - petclinic.war
      - .ebextensions/**/*
       
